<?php
/**
 * WPBakery Page Builder Integration Component.
 *
 * @package TF\Multilingual\Integration\WPBakery
 */

declare( strict_types=1 );

namespace TF\Multilingual\Integration\WPBakery;

use TF\Multilingual\Domain\CustomField\CustomFieldPolicy;
use TF\Multilingual\Domain\CustomField\CustomFieldPolicyRegistry;
use TF\Multilingual\Domain\Media\MediaTranslationResolver;
use WP_Post;

/**
 * Class WPBakeryIntegration
 *
 * Coordinates compatibility between TF Multilingual and WPBakery Page Builder (Visual Composer).
 * Strictly decoupled: operates safely whether WPBakery is installed or absent.
 */
class WPBakeryIntegration {

	/**
	 * Meta key controlling WPBakery editor activation on a post.
	 */
	public const META_JS_STATUS = '_wpb_vc_js_status';

	/**
	 * Meta key storing custom page-level CSS generated by WPBakery.
	 */
	public const META_POST_CUSTOM_CSS = '_wpb_post_custom_css';

	/**
	 * Meta key storing shortcode-level design option CSS generated by WPBakery.
	 */
	public const META_SHORTCODES_CUSTOM_CSS = '_wpb_shortcodes_custom_css';

	/**
	 * Custom field policy registry.
	 *
	 * @var CustomFieldPolicyRegistry
	 */
	private CustomFieldPolicyRegistry $policy_registry;

	/**
	 * Media translation resolver.
	 *
	 * @var MediaTranslationResolver|null
	 */
	private ?MediaTranslationResolver $media_resolver;

	/**
	 * Constructor.
	 *
	 * @param CustomFieldPolicyRegistry      $policy_registry Policy registry.
	 * @param MediaTranslationResolver|null $media_resolver  Optional media translation resolver.
	 */
	public function __construct(
		CustomFieldPolicyRegistry $policy_registry,
		?MediaTranslationResolver $media_resolver = null
	) {
		$this->policy_registry = $policy_registry;
		$this->media_resolver  = $media_resolver;
	}

	/**
	 * Registers WordPress action and filter hooks for WPBakery compatibility.
	 *
	 * @return void
	 */
	public function init_hooks(): void {
		$this->register_field_policies();

		if ( function_exists( 'add_filter' ) ) {
			add_filter(
				'tfml_initial_translation_post_content',
				array( $this, 'filter_initial_translation_post_content' ),
				10,
				3
			);
		}

		if ( function_exists( 'add_action' ) ) {
			add_action(
				'tfml_post_translation_created',
				array( $this, 'on_post_translation_created' ),
				10,
				3
			);
		}
	}

	/**
	 * Removes WordPress action and filter hooks.
	 *
	 * @return void
	 */
	public function remove_hooks(): void {
		if ( function_exists( 'remove_filter' ) ) {
			remove_filter(
				'tfml_initial_translation_post_content',
				array( $this, 'filter_initial_translation_post_content' ),
				10
			);
		}

		if ( function_exists( 'remove_action' ) ) {
			remove_action(
				'tfml_post_translation_created',
				array( $this, 'on_post_translation_created' ),
				10
			);
		}
	}

	/**
	 * Registers default custom field policies for WPBakery metadata in the sovereign registry.
	 *
	 * Defaults:
	 * - _wpb_vc_js_status => SHARE (so translations retain builder mode)
	 * - _wpb_post_custom_css => TRANSLATE (independent per-language custom styling)
	 * - _wpb_shortcodes_custom_css => TRANSLATE (independent shortcode design options)
	 *
	 * Does not overwrite existing administrator-configured policies.
	 *
	 * @return void
	 */
	public function register_field_policies(): void {
		if ( ! $this->policy_registry->has_policy( self::META_JS_STATUS ) ) {
			$this->policy_registry->set_policy( self::META_JS_STATUS, CustomFieldPolicy::SHARE );
		}

		if ( ! $this->policy_registry->has_policy( self::META_POST_CUSTOM_CSS ) ) {
			$this->policy_registry->set_policy( self::META_POST_CUSTOM_CSS, CustomFieldPolicy::TRANSLATE );
		}

		if ( ! $this->policy_registry->has_policy( self::META_SHORTCODES_CUSTOM_CSS ) ) {
			$this->policy_registry->set_policy( self::META_SHORTCODES_CUSTOM_CSS, CustomFieldPolicy::TRANSLATE );
		}
	}

	/**
	 * Checks whether WPBakery Page Builder is currently active in the WordPress environment.
	 *
	 * @return bool True if active.
	 */
	public function is_wpbakery_active(): bool {
		return defined( 'WPB_VC_VERSION' ) || class_exists( 'Vc_Manager' );
	}

	/**
	 * Checks whether a given content string contains WPBakery shortcodes.
	 *
	 * @param string $content Post content string.
	 * @return bool True if content contains WPBakery shortcodes.
	 */
	public function has_wpbakery_content( string $content ): bool {
		return str_contains( $content, '[vc_' ) || str_contains( $content, '[/vc_' );
	}

	/**
	 * Extracts all attachment IDs referenced in WPBakery shortcode attributes.
	 *
	 * Inspects image="ID", background_image="ID", and images="ID1,ID2,...".
	 *
	 * @param string $content Post content string.
	 * @return array<int> Unique list of attachment IDs.
	 */
	public function extract_media_ids( string $content ): array {
		$ids = array();

		// Single image references: image="123" or background_image="123".
		if ( preg_match_all( '/\b(?:image|background_image)=(["\'])(\d+)\1/', $content, $single_matches ) ) {
			foreach ( $single_matches[2] as $match_id ) {
				$int_id = (int) $match_id;
				if ( $int_id > 0 ) {
					$ids[] = $int_id;
				}
			}
		}

		// Multiple image references: images="123,456,789" or images="123, 456".
		if ( preg_match_all( '/\bimages=(["\'])([\d,\s]+)\1/', $content, $multi_matches ) ) {
			foreach ( $multi_matches[2] as $csv ) {
				$parts = explode( ',', $csv );
				foreach ( $parts as $part ) {
					$int_id = (int) trim( $part );
					if ( $int_id > 0 ) {
						$ids[] = $int_id;
					}
				}
			}
		}

		return array_values( array_unique( $ids ) );
	}

	/**
	 * Resolves the localized attachment ID for a target language if mapped.
	 *
	 * @param int    $attachment_id   Source attachment ID.
	 * @param string $target_language Target language code.
	 * @return int Localized attachment ID, or original if unchanged.
	 */
	public function localize_media_id( int $attachment_id, string $target_language ): int {
		if ( $attachment_id <= 0 ) {
			return $attachment_id;
		}

		$localized_id = $attachment_id;
		if ( function_exists( 'apply_filters' ) ) {
			/**
			 * Filters the localized attachment ID for shortcode media replacement.
			 *
			 * @param int    $attachment_id   Original attachment ID.
			 * @param string $target_language Target language code.
			 */
			$mapped = (int) apply_filters( 'tfml_localize_attachment_id', $attachment_id, $target_language );
			if ( $mapped > 0 ) {
				$localized_id = $mapped;
			}
		}

		return $localized_id;
	}

	/**
	 * Localizes shortcode media attributes within WPBakery post content.
	 *
	 * Replaces image="ID", background_image="ID", and images="ID1,ID2" with localized IDs
	 * when applicable, while pre-warming the MediaTranslationResolver cache.
	 *
	 * @param string                      $content         Shortcode content.
	 * @param string                      $target_language Target language code.
	 * @param MediaTranslationResolver|null $resolver       Optional resolver instance.
	 * @return string Content with localized shortcode media attributes.
	 */
	public function localize_shortcode_media(
		string $content,
		string $target_language,
		?MediaTranslationResolver $resolver = null
	): string {
		$active_resolver = null !== $resolver ? $resolver : $this->media_resolver;

		// Pre-warm media cache in a single query for zero N+1.
		if ( null !== $active_resolver ) {
			$media_ids = $this->extract_media_ids( $content );
			if ( ! empty( $media_ids ) ) {
				$active_resolver->prime_cache( $media_ids );
			}
		}

		// Replace single image attributes.
		$single_pattern = '/\b(image|background_image)=(["\'])(\d+)\2/';
		$content        = (string) preg_replace_callback(
			$single_pattern,
			function ( array $matches ) use ( $target_language ): string {
				$attr_name    = $matches[1];
				$quote        = $matches[2];
				$orig_id      = (int) $matches[3];
				$localized_id = $this->localize_media_id( $orig_id, $target_language );

				return sprintf( '%s=%s%d%s', $attr_name, $quote, $localized_id, $quote );
			},
			$content
		);

		// Replace multiple image attributes (e.g. galleries, carousels).
		$multi_pattern = '/\bimages=(["\'])([\d,\s]+)\1/';
		$content       = (string) preg_replace_callback(
			$multi_pattern,
			function ( array $matches ) use ( $target_language ): string {
				$quote    = $matches[1];
				$orig_ids = explode( ',', $matches[2] );
				$new_ids  = array();
				foreach ( $orig_ids as $id_str ) {
					$id = (int) trim( $id_str );
					if ( $id > 0 ) {
						$new_ids[] = $this->localize_media_id( $id, $target_language );
					}
				}

				return sprintf( 'images=%s%s%s', $quote, implode( ',', $new_ids ), $quote );
			},
			$content
		);

		return $content;
	}

	/**
	 * Prepares WPBakery post content for initial translation duplication.
	 *
	 * Copies shortcode layout hierarchy while mapping localized media IDs.
	 *
	 * @param string                      $content         Source content.
	 * @param string                      $target_language Target language code.
	 * @param MediaTranslationResolver|null $resolver       Optional resolver instance.
	 * @return string Localized layout content.
	 */
	public function copy_content_for_translation(
		string $content,
		string $target_language,
		?MediaTranslationResolver $resolver = null
	): string {
		if ( ! $this->has_wpbakery_content( $content ) ) {
			return $content;
		}

		return $this->localize_shortcode_media( $content, $target_language, $resolver );
	}

	/**
	 * Filters the initial post content when creating a translation post.
	 *
	 * If the source post contains WPBakery shortcodes, initializes the draft translation
	 * with the duplicated and localized layout structure so the editorial user does not
	 * need to re-construct the visual builder layout from scratch.
	 *
	 * @param string  $content         Initial content (default empty string).
	 * @param WP_Post $source_post     Source post object.
	 * @param string  $target_language Target language code.
	 * @return string Filtered initial content.
	 */
	public function filter_initial_translation_post_content(
		string $content,
		WP_Post $source_post,
		string $target_language
	): string {
		// If another filter already populated content, respect it.
		if ( '' !== $content ) {
			return $content;
		}

		$source_content = (string) ( $source_post->post_content ?? '' );
		if ( ! $this->has_wpbakery_content( $source_content ) ) {
			return $content;
		}

		$should_copy = true;
		if ( function_exists( 'apply_filters' ) ) {
			/**
			 * Allows disabling or customizing automatic layout copying for WPBakery content.
			 *
			 * @param bool    $should_copy     Whether to copy WPBakery layout (default true).
			 * @param WP_Post $source_post     Source post object.
			 * @param string  $target_language Target language code.
			 */
			$should_copy = (bool) apply_filters(
				'tfml_wpbakery_copy_content_on_translation',
				true,
				$source_post,
				$target_language
			);
		}

		if ( ! $should_copy ) {
			return $content;
		}

		return $this->copy_content_for_translation( $source_content, $target_language );
	}

	/**
	 * Action handler called after a post translation is created.
	 *
	 * Copies initial custom CSS styling from source post as a baseline draft if present,
	 * maintaining strict editorial independence under the TRANSLATE policy.
	 *
	 * @param int    $new_post_id      Newly created translation post ID.
	 * @param int    $source_post_id   Source post ID.
	 * @param string $target_language  Target language code.
	 * @return void
	 */
	public function on_post_translation_created(
		int $new_post_id,
		int $source_post_id,
		string $target_language
	): void {
		if ( ! function_exists( 'get_post_meta' ) || ! function_exists( 'update_post_meta' ) ) {
			return;
		}

		$copy_css = true;
		if ( function_exists( 'apply_filters' ) ) {
			$copy_css = (bool) apply_filters(
				'tfml_wpbakery_copy_custom_css_on_translation',
				true,
				$new_post_id,
				$source_post_id,
				$target_language
			);
		}

		if ( ! $copy_css ) {
			return;
		}

		$css_keys = array(
			self::META_POST_CUSTOM_CSS,
			self::META_SHORTCODES_CUSTOM_CSS,
		);

		foreach ( $css_keys as $key ) {
			$existing_target = get_post_meta( $new_post_id, $key, true );
			if ( empty( $existing_target ) ) {
				$source_val = get_post_meta( $source_post_id, $key, true );
				if ( ! empty( $source_val ) ) {
					update_post_meta( $new_post_id, $key, $source_val );
				}
			}
		}
	}
}
